// Generated by crates/whiphand-protocol (tests/codegen.rs). Do not edit:
// change the Rust types, then run with WHIPHAND_UPDATE_PROTOCOL=1.

import type { ConfigKey, ManualRequest, PartialConfig, RunDetail, RunSummary, WhiphandEvent, Workflow, WorkspaceConfig } from './core-types.ts';

export const PROTOCOL_VERSION = 1;

export const ErrorCode = {
  ParseError: -32700,
  MethodNotFound: -32601,
  InvalidParams: -32602,
  ServerError: -32000,
} as const;

export type Request = { id: number, method: string, params?: unknown, };

export type RpcError = { code: number, message: string, data?: unknown, };

export type Response = { id: number | null, result: unknown, } | { id: number | null, error: RpcError, };

export type Notification = { method: string, params: unknown, };

export type Scope = "project" | "global";

export type JobStatus = "running" | "succeeded" | "failed" | "cancelled";

export type ManualChoice = "continue" | "abort" | "retry";

export type AwaitReason = "turn" | "permission" | "away" | "attention";

export type Stream = "stdout" | "stderr";

export type PtyExitReason = "exit" | "ended";

export type FileComment = { path: string, body: string, };

export type WorkflowFieldProblem = { stepId?: string, field?: string, phrase: string, message: string, };

export type Empty = Record<string, never>;

export type HelloResult = { version: string, protocolVersion: 1, };

export type WorkdirParams = { workdir: string, };

export type WorkflowListEntry = { name: string, path: string, source: Scope, shadowed?: true, workflow?: Workflow, error?: string, };

export type WorkflowRefParams = { workdir: string, name: string, scope?: Scope, };

export type PathResult = { path: string, };

export type UpdateWorkflowParams = { workdir: string, name: string, workflow: Workflow, scope?: Scope, };

export type DeleteWorkflowResult = { deleted: boolean, };

export type CloneWorkflowParams = { workdir: string, name: string, newName: string, scope?: Scope, };

export type ValidateWorkflowParams = { draft: unknown, };

export type ValidateWorkflowResult = { workflow?: Workflow, problems: Array<string>, fieldProblems: Array<WorkflowFieldProblem>, };

export type InitWorkspaceResult = { created: Array<string>, };

export type OptionalWorkdirParams = { workdir?: string, };

export type ToolGroup = "harness" | "support";

export type DoctorRow = { id: string, label: string, group: ToolGroup, runner: boolean, optional: boolean, installed: boolean, version?: string, notes?: Array<string>, url?: string, };

export type ListModelsParams = { refresh?: boolean, };

export type ModelInfo = { id: string, label?: string, description?: string, resolves?: string, };

export type ModelSource = "live" | "fallback" | "unavailable";

export type ModelListRow = { source: ModelSource, models: Array<ModelInfo>, note?: string, };

export type ListModelsResult = Record<string, ModelListRow>;

export type ConfigLayerInfo = { config: PartialConfig, path: string, exists: boolean, };

export type ConfigGetResult = { config: WorkspaceConfig, global: ConfigLayerInfo, project?: ConfigLayerInfo, };

export type ConfigSetParams = { workdir?: string, config: WorkspaceConfig, scope?: Scope, explicitKeys?: ConfigKey[], };

export type OkTrue = { ok: true, };

export type OkResult = { ok: boolean, };

export type AttachmentSource = PathAttachment | Base64Attachment;

export type PathAttachment = { path: string, };

export type Base64Attachment = { name: string, base64: string, };

export type StartRunParams = { workdir: string, workflow: string, inputs?: Record<string, string>, dryRun?: boolean, maxIterations?: number, name?: string, attachments?: Array<AttachmentSource>, };

export type JobIdResult = { jobId: string, };

export type ResumeRunParams = { workdir: string, runId: string, freshSession?: boolean, extraIterations?: number, };

export type JobParams = { jobId: string, };

export type RunRefParams = { workdir: string, runId: string, };

export type CancelRunParams = JobParams | RunRefParams;

export type DeleteRefusal = "locked" | "running" | "missing";

export type DeleteRunResult = { deleted: boolean, reason?: DeleteRefusal, };

export type SetRunLockedParams = { workdir: string, runId: string, locked: boolean, };

export type SetRunLockedResult = { locked: boolean, };

export type RenameRunParams = { workdir: string, runId: string, name: string | null, };

export type RenameRunResult = { renamed: boolean, name?: string, };

export type PruneRunsParams = { workdir: string, max: number, };

export type PruneFailure = { runId: string, reason: string, };

export type PruneRunsResult = { deleted: Array<string>, failed?: Array<PruneFailure>, };

export type ResolveManualParams = { jobId: string, stepId: string, choice: ManualChoice, note?: string, comments?: Array<FileComment>, };

export type ListRunsResult = RunSummary[];

export type GetRunResult = RunDetail | null;

export type ReadRunLogParams = { workdir: string, runId: string, offset?: number, limit?: number, fromEnd?: boolean, beforeByte?: number, };

export type GetWorkingDiffParams = { workdir: string, 
/**
 * Diff this run's worktree instead of the workspace.
 */
runId?: string, };

export type ReadRunLogResult = { lines: Array<string>, total?: number, truncated?: boolean, startByte?: number, atStart?: boolean, };

export type DiffStatus = "added" | "modified" | "deleted" | "renamed";

export type WorkingDiffFile = { path: string, oldPath?: string, status: DiffStatus, additions: number, deletions: number, binary: boolean, patch?: string, truncated?: boolean, };

export type WorkingDiff = { files: Array<WorkingDiffFile>, filesTruncated?: number, patchesOmitted?: number, };

export type GetWorkingDiffResult = WorkingDiff | null;

export type ArtifactEncoding = "utf8" | "base64";

export type ArtifactRefParams = { workdir: string, runId: string, name: string, };

export type ReadArtifactParams = { workdir: string, runId: string, name: string, encoding?: ArtifactEncoding, };

export type ReadArtifactResult = { content: string, size: number, mtimeMs: number, };

export type WriteArtifactParams = { workdir: string, runId: string, name: string, content: string, expectedMtimeMs?: number, };

export type WriteArtifactResult = { mtimeMs: number, };

export type StatArtifactResult = { size: number, mtimeMs: number, };

export type PtyInputParams = { jobId: string, 
/**
 * Base64.
 */
data: string, };

export type PtyResizeParams = { jobId: string, cols: number, rows: number, };

export type RecentWorkspace = { path: string, lastOpenedAt: string, pinned?: boolean, identityKey?: string, };

export type WindowState = { width: number, height: number, x: number, y: number, };

export type ThemePreference = "system" | "light" | "dark";

export type RunsRetention = { maxPerWorkspace: number, };

export type WorkspaceMemory = { identityKey?: string, lastWorkflow?: string, 
/**
 * Workflow name to its last inputs.
 */
lastInputs: Record<string, Record<string, string>>, };

export type AppState = { schemaVersion: 1, recentWorkspaces: Array<RecentWorkspace>, window: WindowState | null, lastPage: string | null, theme: ThemePreference, workspaces: Record<string, WorkspaceMemory>, runsRetention: RunsRetention, showOngoingRuns: boolean, };

export type TouchRecentWorkspaceParams = { path: string, };

export type RecentWorkspacesResult = { recentWorkspaces: Array<RecentWorkspace>, };

export type SetWorkspacePinnedParams = { path: string, pinned: boolean, };

export type SetUiStateParams = { window?: WindowState | null, lastPage?: string | null, theme?: ThemePreference, runsRetention?: RunsRetention, showOngoingRuns?: boolean, };

export type ListRecentRunsParams = { limit?: number, };

export type ListRecentRunsResult = Array<RunSummary & { workspace: string; identityKey?: string }>;

export type PtySize = { stepId: string, cols: number, rows: number, };

export type JobSummary = { jobId: string, workdir: string, identityKey?: string, runId?: string, name?: string, status: JobStatus, pty: PtySize | null, pendingManual?: ManualRequest, };

export type PtyAwaiting = { stepId: string, reason: AwaitReason, };

export type PtyScrollback = { stepId: string, cols: number, rows: number, baseIndex: number, trimmed: boolean, chunks: Array<string>, exited: boolean, exitCode?: number, exitReason?: PtyExitReason, awaiting?: PtyAwaiting, };

export type LogLine = { stream: Stream, line: string, };

export type LogScrollback = { baseIndex: number, trimmed: boolean, lines: Array<LogLine>, };

export type JobScrollback = { pty: PtyScrollback | null, logs: LogScrollback, events?: Array<WhiphandEventParams>, };

export type GetJobScrollbackResult = JobScrollback | null;

export type RemoteAccessState = { enabled: boolean, port: number, 
/**
 * Only in the get and rotate results, never in a notification.
 */
token?: string, listening: boolean, error: string | null, clientCount: number, addresses: Array<string>, webRootPresent: boolean, };

export type RemoteAccessSetParams = { enabled?: boolean, port?: number, };

export type WhiphandEventParams = { jobId: string, workdir?: string, identityKey?: string, runId?: string, event: WhiphandEvent, ts: string, seq?: number, };

export type RunStateChangedParams = { jobId: string, workdir?: string, identityKey?: string, runId?: string, status: JobStatus, };

export type PtyStartedParams = { jobId: string, stepId: string, cols: number, rows: number, };

export type PtyDataParams = { jobId: string, 
/**
 * Base64.
 */
data: string, seq?: number, };

export type PtyExitParams = { jobId: string, exitCode: number, reason?: PtyExitReason, };

export type PtyAwaitParams = { jobId: string, stepId: string, awaiting: boolean, reason?: AwaitReason, };

export type StepLogParams = { jobId: string, stream: Stream, line: string, seq?: number, };

export type ManualRequestParams = { jobId: string, runId?: string, request: ManualRequest, };

export type ManualResolvedParams = { jobId: string, stepId: string, choice?: ManualChoice, };

export type RemoteAccessChangedParams = { enabled: boolean, port: number, listening: boolean, error: string | null, clientCount: number, addresses: Array<string>, webRootPresent: boolean, };

export type HelloParams = Empty;
export type ListWorkflowsParams = WorkdirParams;
export type ListWorkflowsResult = WorkflowListEntry[];
export type GetWorkflowParams = WorkflowRefParams;
export type GetWorkflowResult = Workflow;
export type CreateWorkflowParams = WorkflowRefParams;
export type CreateWorkflowResult = PathResult;
export type UpdateWorkflowResult = PathResult;
export type DeleteWorkflowParams = WorkflowRefParams;
export type CloneWorkflowResult = PathResult;
export type InitWorkspaceParams = WorkdirParams;
export type DoctorParams = OptionalWorkdirParams;
export type DoctorResult = DoctorRow[];
export type ConfigGetParams = OptionalWorkdirParams;
export type ConfigSetResult = OkTrue;
export type StartRunResult = JobIdResult;
export type ResumeRunResult = JobIdResult;
export type CancelRunResult = OkResult;
export type DeleteRunParams = RunRefParams;
export type EndSessionParams = JobParams;
export type EndSessionResult = OkResult;
export type ResolveManualResult = OkResult;
export type ListRunsParams = WorkdirParams;
export type GetRunParams = RunRefParams;
export type StatArtifactParams = ArtifactRefParams;
export type PtyInputResult = OkTrue;
export type PtyResizeResult = OkTrue;
export type GetAppStateParams = Empty;
export type GetAppStateResult = AppState;
export type TouchRecentWorkspaceResult = RecentWorkspacesResult;
export type SetWorkspacePinnedResult = RecentWorkspacesResult;
export type SetUiStateResult = OkTrue;
export type ListJobsParams = Empty;
export type ListJobsResult = JobSummary[];
export type GetJobScrollbackParams = JobParams;
export type RemoteAccessGetParams = Empty;
export type RemoteAccessGetResult = RemoteAccessState;
export type RemoteAccessSetResult = RemoteAccessState;
export type RemoteAccessRotateTokenParams = Empty;
export type RemoteAccessRotateTokenResult = RemoteAccessState;
export type AppStateChangedParams = AppState;

/** Every method's params and result. */
export interface MethodMap {
  hello: { params: HelloParams; result: HelloResult };
  listWorkflows: { params: ListWorkflowsParams; result: ListWorkflowsResult };
  getWorkflow: { params: GetWorkflowParams; result: Workflow };
  createWorkflow: { params: CreateWorkflowParams; result: CreateWorkflowResult };
  updateWorkflow: { params: UpdateWorkflowParams; result: UpdateWorkflowResult };
  deleteWorkflow: { params: DeleteWorkflowParams; result: DeleteWorkflowResult };
  cloneWorkflow: { params: CloneWorkflowParams; result: CloneWorkflowResult };
  validateWorkflow: { params: ValidateWorkflowParams; result: ValidateWorkflowResult };
  initWorkspace: { params: InitWorkspaceParams; result: InitWorkspaceResult };
  doctor: { params: DoctorParams; result: DoctorResult };
  listModels: { params: ListModelsParams; result: ListModelsResult };
  configGet: { params: ConfigGetParams; result: ConfigGetResult };
  configSet: { params: ConfigSetParams; result: ConfigSetResult };
  startRun: { params: StartRunParams; result: StartRunResult };
  resumeRun: { params: ResumeRunParams; result: ResumeRunResult };
  cancelRun: { params: CancelRunParams; result: CancelRunResult };
  deleteRun: { params: DeleteRunParams; result: DeleteRunResult };
  setRunLocked: { params: SetRunLockedParams; result: SetRunLockedResult };
  renameRun: { params: RenameRunParams; result: RenameRunResult };
  pruneRuns: { params: PruneRunsParams; result: PruneRunsResult };
  endSession: { params: EndSessionParams; result: EndSessionResult };
  resolveManual: { params: ResolveManualParams; result: ResolveManualResult };
  listRuns: { params: ListRunsParams; result: ListRunsResult };
  getRun: { params: GetRunParams; result: GetRunResult };
  readRunLog: { params: ReadRunLogParams; result: ReadRunLogResult };
  getWorkingDiff: { params: GetWorkingDiffParams; result: GetWorkingDiffResult };
  readArtifact: { params: ReadArtifactParams; result: ReadArtifactResult };
  writeArtifact: { params: WriteArtifactParams; result: WriteArtifactResult };
  statArtifact: { params: StatArtifactParams; result: StatArtifactResult };
  ptyInput: { params: PtyInputParams; result: PtyInputResult };
  ptyResize: { params: PtyResizeParams; result: PtyResizeResult };
  getAppState: { params: GetAppStateParams; result: GetAppStateResult };
  touchRecentWorkspace: { params: TouchRecentWorkspaceParams; result: TouchRecentWorkspaceResult };
  setWorkspacePinned: { params: SetWorkspacePinnedParams; result: SetWorkspacePinnedResult };
  setUiState: { params: SetUiStateParams; result: SetUiStateResult };
  listRecentRuns: { params: ListRecentRunsParams; result: ListRecentRunsResult };
  listJobs: { params: ListJobsParams; result: ListJobsResult };
  getJobScrollback: { params: GetJobScrollbackParams; result: GetJobScrollbackResult };
  remoteAccessGet: { params: RemoteAccessGetParams; result: RemoteAccessGetResult };
  remoteAccessSet: { params: RemoteAccessSetParams; result: RemoteAccessSetResult };
  remoteAccessRotateToken: { params: RemoteAccessRotateTokenParams; result: RemoteAccessRotateTokenResult };
}

export type MethodName = keyof MethodMap;

/** Every notification's params. */
export interface NotificationMap {
  whiphandEvent: WhiphandEventParams;
  runStateChanged: RunStateChangedParams;
  ptyStarted: PtyStartedParams;
  ptyData: PtyDataParams;
  ptyExit: PtyExitParams;
  ptyAwait: PtyAwaitParams;
  stepLog: StepLogParams;
  manualRequest: ManualRequestParams;
  manualResolved: ManualResolvedParams;
  remoteAccessChanged: RemoteAccessChangedParams;
  appStateChanged: AppStateChangedParams;
}

export type NotificationName = keyof NotificationMap;
